### PR TITLE
Add Dockerfile to create production builds of Joule

### PR DESCRIPTION
**Pull request by bumi**
Started a Dockerfile that can be used to create production builds of joule. 
This should make it easier for people to create and verify production builds.

I am not sure what the best approach for this is using docker. 
Currently the docker image needs to be created: 

    $ docker build -t joule .

And then the production .zip can be copied to the host machine:

    $ docker run --rm -v "$(pwd):/out" joule sh -c "cp /app/dist-prod/joule*.zip /out"

joule-vx.x.x.zip will then be in the project root folder.

Alternatively run the production build from the current working directory:

    $ docker run --rm -v "$(pwd):/build" joule sh -c "cd /build && yarn && yarn build"

All build dependencies run in Docker but will create the build `dist-prod` on the host.

### CODE REVIEW

**Comment by bumi** [comment]
Actually I think this does not make sense and this is way simpler and we do not need a Dockerfile at all: 

```
$ docker run --rm -v "$(pwd):/app" node:lts sh -c "apt-get update && apt-get install zip --yes &&cd /app && yarn install && yarn build && yarn package:prod
```
this mounts the current directory in a node container, installs zip, builds the production dist and zips the package using the script in #269

This does not require anything on the host machine (except docker) and creates a verifiable build. (to solve #260)

**Comment by wbobeirne** [comment]
That's pretty slick. I think I still like the Dockerfile approach, since we can split it out into multiple lines and it's a bit easier to parse that way. It would still have the same dependency requirements (just docker) but be a bit easier to maintain. It's also nice for people who want to develop in a Docker container, and don't want to install node et al on their host machine.

Thanks for getting started on this, I'll try to play with this and #269 a bit this week and confirm the builds are nice'n'deterministic.

**Comment by bumi** [comment]
OK. great! 

I'd combine those commands in a build script and the docker command would then be something like: 
`docker run --rm ----volume="$(pwd):/app" --workdir="/app" node:lts /app/scripts/build`
It depends a bit on how we want to build the deterministic zip (#269 or something else) 

If we add the Dockerfile to allow people developing with it I think we should somehow make sure it can easily be used to run dev commands. 

But in the end the only dependency is node and `yarn install` needs to run. This can also easily be done from within the default node container: 
`$ docker run --rm -v "$(pwd):/app" --workdir="/app" -t -i node:lts bash`  - this gives you a shell to run the yarn commands.

**Comment by bumi** [comment]
This actually also looks quite nice for our usecase: https://earthly.dev/

**Comment by bumi** [comment]
@wbobeirne any thoughts on this? I think it would be nice to get joule back into the firefox store.

**Comment by bumi** [comment]
@wbobeirne sorry for bothering, but do you have any thoughts on this?
This should work and if we consider joule useful and want to progress I think it would be nice to get it back in the browser add-on stores.

**Comment by wbobeirne** [comment]
I've carried this work on in #295, unfortunately despite the name, `strip-nondeterminism` does not do as advertised. I've tried also passing it `--timestamp` but it doesn't seem to rewrite the file last modified times. The zip gets a new hash every time.

Going to close this PR and continue iterating in the new PR.

**Pull request closed without merging**
