### PR TITLE
Add Groestlcoin

### PR DESCRIPTION
**Pull request by HashEngineering**
### Description

This PR adds support for Groestlcoin (ticker: GRS), which is a coin similar to Bitcoin in that it support segwit and has an infrastructure that includes Lightning Network.

The Groestlcoin ecosystem has equivalents of LND (also called LND), Lighting App (GRS Lightning App) and Zap Desktop (ZAP GRS Desktop).  All of these are currently on version 0.8.2 of `lnd`.  Testing was performed on all of these software before submitting this PR.

### Steps to Test

1. Install extension normally
2. Connect to an internal or external Groestlcoin Lightning Network node
3. Test

### Screenshots
The Joule extension with this PR is connected to a ZAP (GRS) Desktop app.
joule-ext-grs

### CODE REVIEW

**Comment by wbobeirne** [comment]
Hey, thanks for the PR! Code looks good to me but I'll want to run it locally before merging just to make sure.

What's the state of Groestlcoin's network? Is there a 1ml-like explorer that shows who's online?

**Comment by gruve-p** [comment]
Hey, you can find all LN related things for GRS on: 
https://www.groestlcoin.org/ln/ 
https://www.groestlcoin.org/22nd-december-2019-release/

**Comment by gruve-p** [comment]
@wbobeirne Do you need any help with testing ?

**Comment by jamaljsr** [comment]
Hey @gruve-p, why not just fork the joule repo, then modify it as much as you want? It looks like you've already used this approach for many other bitcoin/ln projects. 

From looking at the GRS mainnet LN [explorer](https://lnmainnet.groestlcoin.org/), there's only 10 channels, 7 nodes, and a total network capacity of $0.07 usd. Not much activity going on there.

Adding GRS support to this repo means that the maintainers are committing to ongoing support of that coin for the future. 

My personal opinion would be to not have GRS added to this repo, for the reasons stated above. The fork approach which you can maintain yourself feels like the better strategy.

**Comment by gruve-p** [comment]
Hey @jamaljsr, Decred was also merged that is why we send a PR. How many channels and nodes do they have (asking out of curiousity) ? I can't find a lightning network explorer for Decred.

Forking this project is not an issue for us. Let us know if you want us to go through this route @wbobeirne . If so, then you can close this PR.

**Comment by wbobeirne** [comment]
Nah, no need to fork at this point. If ever there comes a feature that a chain would need specifically implemented, I would say they should fork. But in its current state, this is just as easy to support as Litecoin or Decred.

Apologies on my delay for merging, I'll definitely get this tested and in tonight. Can't promise when the next extension store release will be though, that might still be a little bit off.

**Pull request merged**
